### PR TITLE
Added Predis driver

### PR DESCRIPTION
**Pull request by jaredtking**
The purpose of this PR is to add a Redis driver that supports Predis, which I needed recently. While the included Redis driver is great, it requires that the phpredis extension is installed. Predis is a nice alternative for those that cannot or do not want to install a PHP extension.

I implemented the driver by copying as much as I could from the existing Redis driver. Is there any interest in adding this to the Stash library? Looking forward to any feedback!

P.S. Stash is an excellent library. Really nice work. :)

### CODE REVIEW

**Comment by tedivm** [comment]
I'm very much interested in this, thank you! We'll need to figure out why this is failing on HHVM before I can include it in a release though.

**Comment by jaredtking** [comment]
The HHVM failures seem to be non-deterministic. The most recent build is now green. It seems to be related to the FileSystem driver tests so not sure if it's something I did in this PR...any thoughs?

**Comment by tedivm** [comment]
I figured out the HHVM issues and have them resolved, so that shouldn't hold this ticket up.

However, to keep with convention I'd like a bit of a change. With the Memcache and SQLite drivers, where there are multiple extensions or subdrivers, Stash has one driver that developers access and then subdrivers behind the scenes that get used. I'd like to follow that model here, defaulting to the extension and falling back on the predis driver (with options allowing developers to specify explicitly what they want).

**Comment by Bilge** [comment]
If you'd like a bit of a change can you not make that change yourself? It doesn't make sense to hold up this PR indefinitely over some minutiae.

**Comment by tedivm** [comment]
@Bilge, instead of complaining about "minutiae" put your money where your mouth is and handle it yourself if you really want to.

@jaredtking, would you mind rebasing against master to clean up some merge conflicts?

**Comment by Bilge** [comment]
@tedivm Fuck you.

**Comment by tedivm** [comment]
@blige - I've blocked you from contributing to projects I run and have reported you to Github. 

Have a nice day!

**Pull request closed without merging**
