### PR TITLE
Added Predis driver

### PR DESCRIPTION
**Pull request by theUniC**
Hi,

This PR adds a new driver based on **[predis](https://github.com/nrk/predis)**. Any improvements are very welcome!

Best,
Christian.

### CODE REVIEW

**Comment by theUniC** [comment]
@tedivm Any thoughts?

**Comment by sagikazarmark** [comment]
Isn't it a duplicate of #211?

**Comment by tedivm** [comment]
Sorry for the delay in response.

if you look at the Memcache and SQLite drivers you'll see that we try to abstract away the differences between backend implementations. For example, php has both the memcache and memcached extensions, but Stash only has one memcached driver which picks the extension in the background. With SQLite there is one driver, but two subdrivers behind that for difference sqlite versions. With the APC driver the code figures out which API (apc or apcu) to use and picks accordingly.

What I would like to see here is the redis extension and predis classes to be abstracted behind the single Redis driver. This can most easily be done by creating simpler "sub drivers" that the main driver can pick based on circumstances (if extension is available use that, if not fall back to predis, while also allowing devs to override to select there own).

This is the reason I rejected #211, and if you were to solve that here I would happily merge your request.

**Comment by sagikazarmark** [comment]
Take a look at this implementation: https://github.com/bernardphp/bernard/tree/master/src/Driver

It tries to do similar abstractions.

**Comment by theUniC** [comment]
OK! Will do it!

**Pull request closed without merging**
