### PR TITLE
Adding way to determine if driver is persistent or not

### PR DESCRIPTION
**Pull request by davereid**
Fixes https://github.com/tedious/Stash/issues/235

This is built on top of https://github.com/tedious/Stash/pull/234, which should be merged first.

This would be an API change if the driver hasn't extended the AbstractDriver class (which is also new).

### CODE REVIEW

**Comment by tedivm** [comment]
Can you rebase against master so I can view just your changes? You seem to have these commits as well as that last pull requests mixed in.

**Comment by tedivm** [comment]
Eh screw it, I just read it, looks good.

**Comment by davereid** [comment]
Awesome, thanks @tedivm! Is there a way I can help update the documentation for the new AbstractDriver and isPersistent() method?

**Comment by tedivm** [comment]
I can always use documentation help- the Stash site isn't as up to date as I'd like. They're in [this repository](https://github.com/tedious/www.stashphp.com), and it's rst format.

**Pull request merged**
