### PR TITLE
Wincache driver support

### PR DESCRIPTION
**Pull request by vincent**

### CODE REVIEW

**Comment by carbontwelve** [comment]
Is there any chance of this making it into the master?

**Comment by vincent** [comment]
Is there a way to load the wincache extension on Travis ?

**Comment by carbontwelve** [comment]
@vincent I was wondering that last night; wincache is Windows only as far as I know, it might have to be a unit test that's allowed to fail in travis?

**Comment by vincent** [comment]
yes @carbontwelve it's windows only afaik.
I don't know what could be the best option about this.

@tedivm if you have an idea I should implement, please let me know.

**Comment by carbontwelve** [comment]
Just to add to the discussion, the caching layer in Laravel supports Wincache as shown [here](https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Session/SessionManager.php#L134), but it doesn't [look like](https://github.com/laravel/framework/tree/7f62d81acb2001faafb21a32544464ebfc92476c/tests/Cache) they have a unittest for it.

**Comment by tedivm** [comment]
Well at this point I'm reasonably sure this driver is no longer up to date with the DriverInterface- this pull request will need to be updated.

Which comes to the main reason why I've been avoiding accepting it. I am not comfortable having code that can't be reasonably tested as part of this package and I was really hoping travis ci would get proper windows support, but it does not appear to be the case.

If someone updates this *and confirms it's passing tests on their machines* I'll reconsider merging it in.

**Pull request closed without merging**
