### PR TITLE
feat: remove deprecation warning for Redis delete

### PR DESCRIPTION
**Pull request by andheiberg**
https://github.com/phpredis/phpredis#del-delete-unlink

> Note: delete is an alias for del and will be removed in future versions of phpredis.

### CODE REVIEW

**Comment by rossdeane** [comment]
@andheiberg the tests have failed 😛

**Comment by andheiberg** [comment]
@rossdeane 🤔frustratingly it doesn't tell me exactly what the problem is in the log. I have to setup a redis server to test locally. It will sadly have to be some other day.

**Comment by tedivm** [comment]
Yeah the fact that it actually segfaults is definitely interesting.

**Comment by tedivm** [comment]
I'm wondering if it may be a Travis-CI issue- I've been debating moving this project to CircleCI and may do that just to get this tested.

**Comment by tedivm** [comment]
I've rebuild the test suite to work on Github- please rebase against the main branch and reopen this pull request if you're still interested in having it merged. Thank you!

**Pull request closed without merging**
