### PR TITLE
Feature/pool disable

### PR DESCRIPTION
**Pull request by alexbowers**
Documentation edit has been made: https://github.com/tedious/www.stashphp.com/pull/2

### CODE REVIEW

**Comment by alexbowers** [comment]
Unsure why this has failed, but it failed on a test that isn't related to anything i've worked on. Any ideas?

**Comment by alexbowers** [comment]
@tedivm Any update on merging this PR?

**Comment by tedivm** [comment]
I posted in the issue. I don't understand why the "forceMiss" is needed, especially since each function you added it to already supposed the "isDisabled" flag.

**Comment by alexbowers** [comment]
Unfortunately, the isDisabled() flag causes unwanted side effects, such as $item->get() returning null.

https://github.com/alexbowers/Stash/blob/feature/pool-disable/src/Stash/Item.php#L234-L236

The effect I am looking for is to force it to miss the cache, so that it gets updated every time.

This is so that our clients in the admin system can 'disable' the cache, without any code changes being needed, and the cache is still there for if they decide to reenable it.

**Comment by tedivm** [comment]
The use case you're looking for is *exactly* what the ephemeral driver is for. It stores all data in an array that disappears when the script finishes running, but allows for developers to build code assuming the caching system is alive and kicking. Since it does allow per-request caching it also has some performance benefits while still being useful for development or "cache disabled" situations.

**Comment by alexbowers** [comment]
This is a feature we would be looking at placing on a live server where
using the file system or apc driver is what we will be using. Having a
conditional to change the driver if disabled feels msssy

**Comment by tedivm** [comment]
I don't see how it's messy. The ephemeral driver is added by default if no other driver is added to the system. If the cache is disabled then don't inject the filesystem or apc driver and you're good to go.

**Comment by alexbowers** [comment]
There is also the use case that whilst in testing on the site we want the
data to be stored but overwritten on requests but when caching is turned
back on it shouldn't have to fetch all the same cached items again. Which
under ephemeral system isn't possible.

**Comment by alexbowers-tecmark** [comment]
```php
<?php

	$driver = new Stash\Driver\FileSystem();
	$driver->setOptions(['path' => './cache']);

	$pool = new Stash\Pool();

	if(!isCacheDisabled()) {
		$pool->setDriver($driver);
	}

	...



	---------

	$driver = new Stash\Driver\FileSystem();
	$driver->setOptions(['path' => '.cache']);
	$pool = new Stash\pool();

	$pool->setDriver($driver);
	$pool->disable(isCacheDisabled());

	...
```

Example use cases, the top one is with the current method, the bottom one is my pull request. TO me the second one is more readable as to what happens

**Comment by alexbowers-tecmark** [comment]
@tedivm you can delete this PR if you want.

**Pull request closed without merging**
