### PR TITLE
Updates to the APC Driver

### PR DESCRIPTION
**Pull request by tedivm**
This updates the APC driver, allowing the use (and testing against) of the APCu extension on modern versions of PHP.

### CODE REVIEW

**Comment by layanto** [comment]
This still rely on APC backward compatibility of APCu where all apc_* functions internally call apcu_* functions. APC backward compatibility is included by default for APCu on PHP5.5 and PHP5.6. But for PHP7, APC backward compatibility is not included by default (and still not working on Windows). Any chance to update the APC driver to check for existence of apcu_fetch function and if so use the apcu_* functions with fallback to apc_* functions?

**Comment by layanto** [comment]
Similar to
https://github.com/illuminate/cache/blob/master/ApcWrapper.php

**Comment by tedivm** [comment]
Can you open this as a new issue, rather than commenting here in this closed one?

**Comment by tedivm** [comment]
Also, I'm currently waiting on Travis-CI to fix this PHP7 build. At the moment we can't test the apcu stuff on Travis due to them having disabled pecl on their php7 machines.

**Pull request merged**
