### PR TITLE
update redis delete function

### LINKED ISSUE #392: Function Redis::delete() is deprecated
found in
https://github.com/tedious/Stash/blob/8f1d28c765b257b05e932c28ad75c809e34fe12c/src/Stash/Driver/Redis.php#L219

see https://github.com/phpredis/phpredis/blob/148bf373b7a0d276f6f6fd1ec1e6b9407fba6497/README.markdown#del-delete-unlink

### PR DESCRIPTION
**Pull request by tedivm**
resolves #392

### CODE REVIEW

**Comment by nicholasruunu** [comment]
Any news on this @tedivm? Let me know if I can help.

**Comment by ashenwolf** [comment]
Any updates? Is there any help needed to roll it out as it is a blocker for me now and I would like to avoid creating own fork...

**Comment by nicholasruunu** [comment]
@ashenwolf To avoid a fork for now, you could just copy and replace the Redis driver and make the change above.

**Comment by saschanos** [comment]
@tedivm, is there any news on this?

**Pull request merged**
